site_name: Документация по Kia Sportage 5 Turbo
site_url: https://kia-sportage-docs.github.io/kia-sport5-docs/
theme:
  name: material
  language: ru
  icon:
    annotation: material/arrow-right-circle
  favicon: images/apple-touch-icon-152x152.png
  features:
    - navigation.indexes
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html  
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.blocks.caption

plugins:
  - glightbox
  - search
  - open-in-new-tab

nav:
  - 'О ресурсе': index.md
  - 'Выбор и сравнение': versions.md
  - 'Известные проблемы' : issue.md
  - 'Эксплуатация':
    - 'Новая машина': expluatation/new_car.md
    - 'Инструкции по эксплуатации': expluatation/manuals.md 
    - 'Аксессуары': part/accessories.md
  - 'Доработки':
    - 'Обогрев руля': improvement/wheel-heating.md
    - 'Шторка в багажник': improvement/trunk-curtain.md
  - 'ТО и ремонты':
    - 'График ТО': service/to.md
    - 'Технические жидкости': service/oil.md
    - 'Инструкции по ремонту и обслуживанию':
      - 'Электросхемы':
        - service/manuals/electrical_circuits/index.md
        - 'Схема блока IBU': service/manuals/electrical_circuits/ibu.md
        - 'Схема блока ICU': service/manuals/electrical_circuits/icu.md
        - 'Схема предохранителей': service/manuals/electrical_circuits/fuse.md
      - 'Коды цвета кузова': service/manuals/colors.md
      - 'Устранение проблем с турбиной': service/manuals/turbine.md
      - 'Устранение проблем с обогревом зеркал': service/manuals/glass-heat.md
      - 'Параметры шин и дисков': service/manuals/wheels.md
  - 'Русификация': translate.md
  - 'Номера запчастей':
    - part/index.md
    - 'Фильтры': part/filters.md
    - 'Мотор': part/motor.md
    - 'Топливная система': part/fuel.md
    - 'Подвеска': part/suspension.md
    - 'Интерьер': part/interior.md
    - 'Экстерьер и кузовыне элементы' : part/exterior.md
    - 'Электрика': part/electric.md
    - 'Прочее': part/other.md
    - 'Аксеcсуары': part/accessories.md
  - 'FAQ': faq.md